name: popcorn_test
version: ${version}
main: dev.kokiriglade.testplugin.TestPlugin
description: Popcorn Test Plugin
authors:
  - kokiriglade
api-version: ${apiversion}
load: STARTUP
dependencies:
    server:
        popcorn:
            load: BEFORE
            required: true
            join-classpath: true
